# Generated by Django 4.2.14 on 2024-07-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=250)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("size", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "property_type",
                    models.CharField(
                        choices=[("casa", "Casa"), ("apto", "Apto")],
                        default="apto",
                        max_length=5,
                    ),
                ),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("bathrooms", models.IntegerField(blank=True, null=True)),
                ("parking_spaces", models.IntegerField(blank=True, null=True)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                ("is_furnished", models.BooleanField(default=False)),
            ],
        ),
    ]
