# Generated by Django 4.2.14 on 2024-08-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="antiguedad",
            field=models.CharField(
                choices=[
                    ("five_years", "menor5"),
                    ("five_ten_years", "cincoydiez"),
                    ("ten_years", "masdediez"),
                ],
                default="five_years",
                max_length=15,
            ),
        ),
    ]
